name = "fileverse-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fileverse-db"
database_id = ""
migrations_dir = "migrations"

[triggers]
crons = ["*/2 * * * *", "*/1 * * * *"]

[vars]
NODE_ENV = "production"
API_KEY = ""

[observability]
enabled = true
